apiVersion: carto.run/v1alpa1
kind: Workload
metadata:
  name: my-java-fn
  labels:
    apps.tanzu.vmware.com/workload-type: workload-type
    app.kubernetes.io/part-of: my-java-fn
spec:
  source:
    git:
      url: git-source-url
      ref:
        branch: git-branch-name